version: 2
jobs:
  build:
    docker:
      - image: rust:slime
        user: root
        environment:
          DENO_INSTALL: "/root/.deno"
    working_directory: /app

    steps:
      - checkout
      - run:
        name: Setup docker
        command: |
          apt-get update
          apt-get install -y python3
          update-alternatives --install /usr/bin/python python /usr/bin/python3 1 \
              && python --version
      - run:
        name: build deno
        command: |
          cd deno/cli && cargo install --path .
          deno --version
  test:
    steps:
      - run:
          name: test code
          command: |
            echo test

workflows:
  version: 2
  build:
    jobs:s
      - build
      - test

