version: 2.1
executors:
  deno-runtime:
    docker:
      - image: rust:slim
        user: root
        environment:
          DENO_INSTALL: "/root/.deno"
commands:
  docker:
    description: "deploy repo"
    steps:
      - run: echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t maxtnt/deno:experiment -f ./docker/Dockerfile
      - run: docker push maxtnt/deno:experiment

  welcome:
    description: "A very simple command for deno check"
    steps:
      - run: deno run https://deno.land/std@v0.41.0/examples/welcome.ts
jobs:
  build:
    executor: deno-runtime
    steps:
      - checkout
      - run: apt-get update && apt-get install -y python3 git && apt-get clean
      - run: update-alternatives --install /usr/bin/python python /usr/bin/python3 1 && python --version
      - run: git submodule update --init
      - run: cd cli && cargo install --path . && deno --version
      - welcome
  deploy:
    executor: deno-runtime
    steps:
      - docker

workflows:
  build-test:
    jobs:
      - build
      - deploy